// <auto-generated />
using System;
using ApiHelth.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiHelth.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiHelth.Models.Atendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHoraChegada")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumeroSequencial")
                        .HasColumnType("int");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("StatusAtendimentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("StatusAtendimentoId");

                    b.ToTable("Atendimentos");
                });

            modelBuilder.Entity("ApiHelth.Models.Especialidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Especialidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Clínico Geral"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Cardiologia"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Ortopedia"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Pediatria"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Ginecologia"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Neurologia"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Dermatologia"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Oftalmologia"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Psiquiatria"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Otorrinolaringologia"
                        });
                });

            modelBuilder.Entity("ApiHelth.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("ApiHelth.Models.StatusAtendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("StatusAtendimentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Aguardando"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Em Triagem"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Aguardando Atendimento Médico"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Em Atendimento"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Em Observação"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Finalizado"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Cancelado"
                        });
                });

            modelBuilder.Entity("ApiHelth.Models.Triagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("AtendimentoId")
                        .HasColumnType("int");

                    b.Property<int>("EspecialidadeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PressaoArterial")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sintomas")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId")
                        .IsUnique();

                    b.HasIndex("EspecialidadeId");

                    b.ToTable("Triagens");
                });

            modelBuilder.Entity("ApiHelth.Models.Atendimento", b =>
                {
                    b.HasOne("ApiHelth.Models.Paciente", "Paciente")
                        .WithMany("Atendimentos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiHelth.Models.StatusAtendimento", "StatusAtendimento")
                        .WithMany("Atendimentos")
                        .HasForeignKey("StatusAtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("StatusAtendimento");
                });

            modelBuilder.Entity("ApiHelth.Models.Triagem", b =>
                {
                    b.HasOne("ApiHelth.Models.Atendimento", "Atendimento")
                        .WithOne("Triagem")
                        .HasForeignKey("ApiHelth.Models.Triagem", "AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiHelth.Models.Especialidade", "Especialidade")
                        .WithMany("Triagens")
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendimento");

                    b.Navigation("Especialidade");
                });

            modelBuilder.Entity("ApiHelth.Models.Atendimento", b =>
                {
                    b.Navigation("Triagem")
                        .IsRequired();
                });

            modelBuilder.Entity("ApiHelth.Models.Especialidade", b =>
                {
                    b.Navigation("Triagens");
                });

            modelBuilder.Entity("ApiHelth.Models.Paciente", b =>
                {
                    b.Navigation("Atendimentos");
                });

            modelBuilder.Entity("ApiHelth.Models.StatusAtendimento", b =>
                {
                    b.Navigation("Atendimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
